### ISSUE TITLE
[Feature] Dropdown

### ISSUE THREAD

**Issue by Major-Eth** [Major-Eth/yearn-web-lib#7]
# What
Create a basic `<Dropdown />` component.

## Requirements
- The component should be a `<select>` and the options should be `<option>`. If not possible with custom design, adapt.
- The arrow on the right should be overwrite
- The arrow should be animated to turn when open/close
- The `state/set_state` should be sent as props
- The options should be sent as props

## Ressources
[Figma - Dropdown](https://www.figma.com/file/E6mbKP5TkCkSKtAh8q0RA0/Evan's-drafts?node-id=1318%3A45562)

## Notes
We recommand the use of [HeadlessUI](https://headlessui.dev/react/menu) for this (support for keyboard and accessibility stuff)

**Comment by karelianpie** [comment]
Working on this one

**Comment by karelianpie** [comment]
@Major-Eth I have a few questions:

- _"The arrow on the right should be overwrite"_, what do you mean by that?
- _"The arrow should be animated to turn when open/close"_, do we need an actual animation or is it fine that it just changes direction?
- _"The state/set_state should be sent as props"_, is this so that we set the label of the button when the option is clicked?
- _"The options should be sent as props"_, is the type for option an object with value/label?

**Comment by karelianpie** [comment]
Major:

- "The arrow on the right should be overwrite", what do you mean by that? => default <option> <select> on HTML have a chevron integrated. This is poorly customizable, so not great

- "The arrow should be animated to turn when open/close", do we need an actual animation or is it fine that it just changes direction? => Change direction with transition (aka rotation transition)

- "The options should be sent as props", is the type for option an object with value/label? => I think (not 100% sure) this would require a key/value pair, key being the option actually selected, and the associated value being the displayed text

- When we hover an item should there be any different styling? => Same as selected right now, we will finetune after

- "The state/set_state should be sent as props", is this so that we set the label of the button when the option is clicked? Not sure to get what you mean

**Comment by Major-Eth** [comment]
More info:
- If using headlessUI, the arrow overwrite may not be needed
- `state/set_state` means that the users should provide them as props, not internally managed, ex: 
```js
const [selected, setSelected] = React.useState(X);
return (
    <Dropdown selected={selected} setSelected={setSelected} options={OPTIONS} />
);
```
- For the hover, either use primary with 90% opacity or nothing and I will check with Evan how to adapt
